global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "cms-community-backend"
    scheme: https
    metrics_path: /actuator/prometheus
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["cms-community-alb-1106724923.ap-northeast-1.elb.amazonaws.com"]
  - job_name: "alb-cloudwatch"
    metrics_path: /metrics
    static_configs:
      - targets: ["cloudwatch-exporter:9106"]
